---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Install Docker engine and tools
  apt:
    name:
      - docker.io
      - docker-compose
      - containerd
    state: present

- name: Ensure Docker service is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add current user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Verify Docker installation
  command: which docker
  register: docker_check
  changed_when: false

